version: "3.8"

services:
  mongodb:
    container_name: mongo-service
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
      - ./backend/data:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    image: sidraut007/wanderlust-backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    image: sidraut007/wanderlust-frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    container_name: redis-service
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379
    depends_on:
      - mongodb

volumes:
  mongo-data:
